# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          # The following additional scopes may be required:
          #  - read:org      (for organization related metrics)
          #  - read:user     (for user related data)
          #  - read:packages (for some packages related data)
          #  - repo          (optional, if you want to include private repositories)
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: i-Pear
          template: classic
          base: header
          base_indepth: yes
          config_timezone: Asia/Shanghai
          plugin_followup: yes
          plugin_followup_archived: yes
          plugin_followup_sections: user
          plugin_notable: yes
          plugin_notable_from: all
          plugin_notable_repositories: yes
          plugin_notable_skipped: bminor/musl, sawork-2023/aw01-i-Pear, sawork-2023/aw02-i-Pear, sawork-2023/aw03-i-Pear, sawork-2023/aw04-i-Pear, sawork-2023/aw05-i-Pear, sawork-2023/aw06-i-Pear, sawork-2023/aw07-i-Pear, sawork-2023/aw08-i-Pear, sawork-2023/aw09-i-Pear, sawork-2023/awx-i-Pear, unikraft/test-workflows, unikraft/gsoc, unikraft/fork-musl, unikraft/fork-glibc, unikraft/dynamic-apps, unikraft/static-pie-apps
          plugin_notable_types: commit, pull_request
